sonar.projectKey=decyphertek-io_DeCypherTek.ai
sonar.organization=decyphertek-io
sonar.sources=src
sonar.exclusions=**/target/**,**/*.lock,**/dist/**

# This is the name displayed in the SonarCloud UI.
#sonar.projectName=DeCypherTek.ai
#sonar.projectVersion=0.1.0

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
